account/urls.py
from . import views
from django.urls import path


app_name = 'account'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path("logout/", views.logout_view, name="logout"),
]

asc_management_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('hod/', include('hod.urls')),
    path('lecturer/', include('lecturer.urls')),
    path('student/', include('student.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hod/urls.py
from django.urls import path
from . import views


app_name = 'hod'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('add_lecturer',views.add_lecturer, name='add_lecturer'),
    path('manage_lecturer', views.manage_lecturer, name='manage_lecturer'),
    path('add_school', views.add_school, name='add_school'),
    path('add_department', views.add_department, name='add_department'),
    path("manage_department/", views.manage_department, name="manage_department"),
    path('add_session', views.add_session, name='add_session'),
    path("manage_session/", views.manage_session, name="manage_session"),
    path('add_student', views.add_student, name='add_student'),
    path('manage_student', views.manage_student, name='manage_student'),
    path("edit_student/<str:pk>", views.edit_student, name="edit_student"),
    path('add_course', views.add_course, name='add_course'),
    path('manage_course', views.manage_course, name='manage_course'),
    path('set_current_session', views.set_current_session, name='set_current_session'),
    path('set_current_semester', views.set_current_semester, name='set_current_semester'),
]

lecturer/urls.py
from . import views
from django.urls import path

app_name = 'lecturer'
urlpatterns = [
    path('', views.home, name='home'),
    path('take_attendance', views.take_attendance, name='take_attendance')
]

lecturer/models.py
from django.db import models

from account.models import User
# Create your models here.

class LecturerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.LECTURER)
    
    

class Lecturer(User):
    objects = LecturerManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.LECTURER
        return super().save(*args, **kwargs)
    
    
    @property
    def more(self):
        return self.lectureraddition
    
    
    
class LecturerAddition(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    updated_at = models.DateField(auto_now=True)
    title = models.CharField(max_length=50)
    lecturer_number = models.CharField(max_length=50)
    address = models.CharField(max_length=255)

lecturer/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse

from account.models import User
from asc_management.models import Course, Session


# Create your views here.

@login_required
def home(request):
    if request.user.type == User.Types.LECTURER:
        return render(request,'lecturer/home.html')
    else:
        return redirect(reverse('account:logout'))


@login_required
def take_attendance(request):
    if request.user.type == User.Types.LECTURER:
        courses = Course.objects.filter(lecturer=request.user.id)
        current_session = Session.current_session()
        
        context = {'courses': courses}
        return render(request,'lecturer/take_attendance.html', context)
    else:
        return redirect(reverse('account:logout'))

lecturer/templates/lecturer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Student Management System</title>
    {% include 'lecturer/custom_css.html' %}
  </head>
  <!--
`body` tag options:

  Apply one or more of the following classes to to the body tag
  to get the desired effect

  * sidebar-collapse
  * sidebar-mini
-->
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      {% include 'lecturer/navbar.html' %}

      <!-- Main Sidebar Container -->
      {% include 'lecturer/sidebar.html' with user=user id=id %}

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0">
                  {% block page_title %}
                  {% endblock page_title %}
                </h1>
              </div>
              <!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="{% url 'lecturer:home' %}">Home</a></li>
                </ol>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        {% block main_content %} {% endblock main_content %}
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      {% include 'lecturer/footer.html' %}
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    {% include 'lecturer/custom_js.html' %}
  </body>
</html>

lecturer/templates/lecturer/custom_css.html
{% load static %}
<!-- Google Font: Source Sans Pro -->
<link
rel="stylesheet"
href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
/>
<!-- Font Awesome Icons -->
<link
rel="stylesheet"
href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"
/>
<!-- IonIcons -->
<link
rel="stylesheet"
href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
/>
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}" />

lecturer/templates/lecturer/custom_js.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard3.js' %}"></script>

lecturer/templates/lecturer/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

lecturer/templates/lecturer/home.html
{% extends 'lecturer/base.html' %}
{% block page_title %} 
Home 
{% endblock page_title %}
{% load static %}

{% block main_content %}
<section class="content">
  <div class="container-fluid">
    
    
  </div>
</section>

{% endblock main_content %}

lecturer/templates/lecturer/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
        <h4 class="nav-link">Student management system</h4>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}" >
          Logout
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

lecturer/templates/lecturer/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img
        src="{% static 'dist/img/AdminLTELogo.png' %}"
        alt="AdminLTE Logo"
        class="brand-image img-circle elevation-3"
        style="opacity: 0.8"
      />
      <span class="brand-text font-weight-light">Student Management System</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img
            src="{% static 'dist/img/user2-160x160.jpg' %} "
            class="img-circle elevation-2"
            alt="User Image"
          />
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input
            class="form-control form-control-sidebar"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul
          class="nav nav-pills nav-sidebar flex-column"
          data-widget="treeview"
          role="menu"
          data-accordion="false"
          >
          
          <li class="nav-item">
            {% url 'lecturer:home' as home %}
            <a href="{{ home }}" class="nav-link {% if request.path == home %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Home
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:take_attendance' as take_attendance %}
            <a href="{{ take_attendance }}" class="nav-link {% if request.path == take_attendance %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Take Attendance
              </p>
            </a>
          </li>
          
          <li class="nav-item">
            {% url 'lecturer:add_lecturer' as add_lecturer %}
            <a href="{{ add_lecturer }}" class="nav-link {% if request.path == add_lecturer %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add lecturer
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:manage_lecturer' as manage_lecturer %}
            <a href="{{ manage_lecturer }}" class="nav-link {% if request.path == manage_lecturer %} active {% endif %} {% if request.path == edit_lecturer %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage lecturer
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:add_school' as add_school %}
            <a href="{{ add_school }}" class="nav-link {% if request.path == add_school %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add School
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'manage_lecturer' as manage_lecturer %}
            <a href="{{ manage_lecturer }}" class="nav-link {% if request.path == manage_lecturer %} active {% endif %} {% if request.path == edit_lecturer %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage School
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:add_department' as add_department%}
            <a href="{{ add_department }}" class="nav-link {% if request.path == add_department %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Department
                
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:manage_department' as manage_department %}
            <a href="{{ manage_department }}" class="nav-link {% if request.path == manage_department %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage Department
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:add_course' as add_course%}
            <a href="{{ add_course }}" class="nav-link {% if request.path == add_course %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Add Course
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:manage_course' as manage_course %}
            <a href="{{ manage_course }}" class="nav-link {% if request.path == manage_course %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage Course
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:add_session' as add_session%}
            <a href="{{ add_session }}" class="nav-link {% if request.path == add_session %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>Add Session</p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'lecturer:manage_session' as manage_session %}
            <a href="{{ manage_session }}" class="nav-link {% if request.path == manage_session %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Manage Session
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                View Attendance report
                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Students Feedbacks
                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                lecturer Feedbacks
                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Student Leave
                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                lecturer Leave
                
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

lecturer/templates/lecturer/take_attendance.html
{% extends 'lecturer/base.html' %}
{% block page_title %} 
Take Attendance
{% endblock page_title %}
{% load static %}

{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Take Attendance</h3>
      </div>
        <div class="card-body">
          <div class="form-group">
            <label>Course Select</label>
            <select class="form-control" name="course" id="course">
                {% for course in courses %}
                    <option value="{{ course.id }}">{{ course.title }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label>Date</label>
            <input type="date" name="attendance_date" class="form-control" id="attendance_date">
          </div>

          <!-- /.card-body -->
          <div class="form-group">
            {% if messages %}
            
            {% for message in messages %} 
            {% if message.tags == 'error' %}
            <div class="alert alert-danger" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% if message.tags == 'success' %}
            <div class="alert alert-success" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% endfor %} 
            {% endif %}
          </div>
        </div>

        <div class="card-footer">
          <button type="submit" class="btn btn-primary btn-block">
            Fetch Students
          </button>
        </div>
    </div>
  </div>
</section>

{% endblock main_content %}