account/urls.py
from . import views
from django.urls import path


app_name = 'account'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path("logout/", views.logout_view, name="logout"),
]

asc_management_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('hod/', include('hod.urls')),
    path('lecturer/', include('lecturer.urls')),
    path('student/', include('student.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hod/urls.py
from django.urls import path
from . import views


app_name = 'hod'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('add_lecturer',views.add_lecturer, name='add_lecturer'),
    path('manage_lecturer', views.manage_lecturer, name='manage_lecturer'),
    path('add_school', views.add_school, name='add_school'),
    path('add_department', views.add_department, name='add_department'),
    path("manage_department/", views.manage_department, name="manage_department"),
    path('add_session', views.add_session, name='add_session'),
    path("manage_session/", views.manage_session, name="manage_session"),
    path('add_student', views.add_student, name='add_student'),
    path('manage_student', views.manage_student, name='manage_student'),
    path("edit_student/<str:pk>", views.edit_student, name="edit_student"),
    path('add_course', views.add_course, name='add_course'),
    path('manage_course', views.manage_course, name='manage_course'),
    path('set_current_session', views.set_current_session, name='set_current_session'),
    path('set_current_semester', views.set_current_semester, name='set_current_semester'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.home, name='home'),
    path('register_course/', views.register_courses, name='register_course'),
    path('get_courses', views.get_courses, name='get_courses'),
    path('save_courses', views.save_courses, name='save_courses')
]

student/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _

from account.models import User
from asc_management.models import Course, Semester, Session, Department
# Create your models here.

class StudentManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.STUDENT)
        

class Student(User):
    objects = StudentManager()
    
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.STUDENT
        return super().save(*args, **kwargs)
    
    
    @property
    def more(self):
        return self.studentaddition
    
class StudentAddition(models.Model):
    GENDER_CHOICES = (('Male','Male'), ('Female', 'Female'))
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    index_number = models.CharField(max_length=15, null=True, unique=True)
    othername = models.CharField(max_length=20, null=True)
    gender = models.CharField(max_length=10, null=True, choices=GENDER_CHOICES)
    phone_number = PhoneNumberField(null=True)
    dob = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to='Student Profile Picture', blank=True, null=True)
    start = models.ForeignKey(Session, related_name='start_session' , on_delete=models.DO_NOTHING, null=True)
    end = models.ForeignKey(Session, related_name='end_session' ,on_delete=models.DO_NOTHING, null=True)
    address = models.CharField(max_length=255, null=True)
    department = models.ForeignKey(Department, on_delete=models.DO_NOTHING, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.index_number
    
    
    
class RegisteredCourses(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    registration_date = models.DateField(auto_now=False, auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.student.more.index_number

student/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from account.models import User
from asc_management.models import Course


# Create your views here.

@login_required
def home(request):
    if request.user.type == User.Types.STUDENT:
        
        
        
        
        
        return render(request,'student/home.html')
    else:
        return redirect(reverse('account:logout'))


@login_required
def register_courses(request):
    
    if request.user.type == User.Types.STUDENT:
        courses = Course.objects.all()
        context = {'courses': courses}
        return render(request,'student/register_course.html', context)
    else:
        return redirect(reverse('account:logout'))


def get_courses(request):
    courses = Course.objects.all()
    
    return JsonResponse({'courses': list(courses.values())})



def save_courses(request):
    if request.method=='POST':
        post_return = request.POST
        reg_courses = post_return.getlist('course_code[]')
        for reg_course in reg_courses:
            print(reg_course)
        
        
    return HttpResponse('we are here')

student/templates/student/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Student Management System</title>
    {% include 'student/custom_css.html' %}
  </head>
  <!--
`body` tag options:

  Apply one or more of the following classes to to the body tag
  to get the desired effect

  * sidebar-collapse
  * sidebar-mini
-->
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      {% include 'student/navbar.html' %}

      <!-- Main Sidebar Container -->
      {% include 'student/sidebar.html' with user=user id=id %}

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0">
                  {% block page_title %}
                  {% endblock page_title %}
                </h1>
              </div>
              <!-- /.col -->
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="{% url 'student:home' %}">Home</a></li>
                </ol>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        {% block main_content %} {% endblock main_content %}
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->

      <!-- Main Footer -->
      {% include 'student/footer.html' %}
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    {% include 'student/custom_js.html' %}
  </body>
</html>

student/templates/student/custom_css.html
{% load static %}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"/>
<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"/>
<!-- IonIcons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"/>
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}" />

student/templates/student/custom_js.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>

student/templates/student/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

student/templates/student/home.html
{% extends 'student/base.html' %}
{% block page_title %} 
Home 
{% endblock page_title %}
{% load static %}

{% block main_content %}
<section class="content">
  <div class="container-fluid">
    
    
  </div>
</section>

{% endblock main_content %}

student/templates/student/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
        <h4 class="nav-link">Student management system</h4>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}" >
          Logout
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

student/templates/student/register_course.html
{% extends 'student/base.html' %}
{% block page_title %} 
Register Course
{% endblock page_title %}
{% load static %}

{% block main_content %}
<section class="content">
    <div class="container-fluid">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">Register Courses</h3>
                <input type="button" id="add_course" class='btn float-right' value="Add course"/>
            </div>
        </div>
        <div class="card-body">
            <form id="course_form">
                {% csrf_token %}
                <div class="course_field">
                    <div class="each-field row">
                        <div class="col-3">
                            <label>Course code</label>
                            <select class="form-control course_code" data-sub_course_code_id="1" name="course_code[]" title="The course form" class="course_code[]" >
                                <option value="">Select a Course</option>
                                {% for course in courses %}
                                <option value="{{ course.id }}">{{ course.code }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-8">
                            <label>Course title</label>
                            <input id="course_title1" type="text" disabled class="form-control" placeholder="Course title">
                        </div>
                        <div class="col-1">
                            <label >Delete</label>
                            <input value="Remove" type="button" class="form-control btn-danger btn_remove">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary btn-block">
                      Register Courses
                    </button>
                </div>
            </form> 
        </div>
        <!-- /.card-body -->
    </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
    $(document).ready(function(){

        var count = 1;
        var limit = 10;

        $('#add_course').click(function(){
            count++;
            html=`
            <div class="each-field row">
                <br>
                <div class="col-3">
                    <label>Course code</label>
                    <select class="form-control course_code" data-sub_course_code_id="${count}" name="course_code[]" title="The course form" id="course_code${count}" >\
                        <option value="" >Select a course</option>
                        {% for course in courses %}
                        <option value="{{ course.id }}">{{ course.code }}</option>\
                        {% endfor %}
                    </select>
                </div>
                <div class="col-8">
                    <label>Course title</label>
                    <input id="course_title${count}" name='course_title[]' type="text" disabled class="form-control" placeholder="Course title">\
                </div>
                <div class="col-1">
                    <label >Delete</label>
                    <input class="form-control btn-danger btn_remove" value="Remove" type="button" >
                </div>
            </div>`;


            var course_form = $('.course_field');
            
            if (count < limit){
                course_form.append(html);
            } else {
                alert('Cant have more than 10');
            }
        })
        
        $(document).on('click', '.btn_remove', function(){
            $(this).closest('.row').remove();
        });

        $(document).on('change', `.course_code`, function(){
            var $this = $(this);

            var course_code = $this.val();
            var sub_course_code = $this.data('sub_course_code_id');
            //console.log(course_code)
        
            if(course_code != ''){
                $.ajax({
                    type: 'GET',
                    url: "{% url 'student:get_courses' %}",
                    success: function(response){
                        let course_title = ''
                        response.courses.forEach(course=>{
                            if (course.id==course_code){
                                course_title=course.title
                                console.log(course_title)
                                $(`#course_title${sub_course_code}`).val(course_title) 
                                
                            }
                        })
                    },
                    error: function(response){
                        alert('an error happened')
                    }
                })
            }
        })
        $('#course_form').submit(function(e){
            e.preventDefault()
            $.ajax({
                url: "{% url 'student:save_courses' %}",
                method: 'POST',
                data:$(this).serialize(),
                success: function(){
                    alert('Successful')
                }
            })
        })
    })

    
    
</script>

{% endblock main_content %}

student/templates/student/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img
        src="{% static 'dist/img/AdminLTELogo.png' %}"
        alt="AdminLTE Logo"
        class="brand-image img-circle elevation-3"
        style="opacity: 0.8"
      />
      <span class="brand-text font-weight-light">Student Management System</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img
            src="{% static 'dist/img/user2-160x160.jpg' %} "
            class="img-circle elevation-2"
            alt="User Image"
          />
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input
            class="form-control form-control-sidebar"
            type="search"
            placeholder="Search"
            aria-label="Search"
          />
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul
          class="nav nav-pills nav-sidebar flex-column"
          data-widget="treeview"
          role="menu"
          data-accordion="false"
          >
          
          <li class="nav-item">
            {% url 'student:home' as home %}
            <a href="{{ home }}" class="nav-link {% if request.path == home %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Home
              </p>
            </a>
          </li>
          <li class="nav-item">
            {% url 'student:register_course' as register_course %}
            <a href="{{ register_course }}" class="nav-link {% if request.path == register_course %} active {% endif %}">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Register Courses
                
              </p>
            </a>
          </li>
          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>