account/urls.py
from . import views
from django.urls import path


app_name = 'account'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path("logout/", views.logout_view, name="logout"),
]

asc_management_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('hod/', include('hod.urls')),
    path('lecturer/', include('lecturer.urls')),
    path('student/', include('student.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hod/urls.py
from django.urls import path
from . import views


app_name = 'hod'
urlpatterns = [
    path('home/', views.home, name="home"),
    path('add_lecturer',views.add_lecturer, name='add_lecturer'),
    path('manage_lecturer', views.manage_lecturer, name='manage_lecturer'),
    path('add_school', views.add_school, name='add_school'),
    path('add_department', views.add_department, name='add_department'),
    path("manage_department/", views.manage_department, name="manage_department"),
    path('add_session', views.add_session, name='add_session'),
    path("manage_session/", views.manage_session, name="manage_session"),
    path('add_student', views.add_student, name='add_student'),
    path('manage_student', views.manage_student, name='manage_student'),
    path("edit_student/<str:pk>", views.edit_student, name="edit_student"),
    path('add_course', views.add_course, name='add_course'),
    path('manage_course', views.manage_course, name='manage_course'),
    path('set_current_session', views.set_current_session, name='set_current_session'),
    path('set_current_semester', views.set_current_semester, name='set_current_semester'),
]

hod/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from account.models import User

# Create your models here.

class HodManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.HOD)

class Hod(User):
    objects = HodManager()
    class Meta:
        proxy = True
        
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Types.HOD
        return super().save(*args, **kwargs)
    
    @property
    def more(self):
        return self.hodaddition
    
class HodAddition(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    updated_at = models.DateField(auto_now=True)

hod/views.py
from django.db import IntegrityError
from django.shortcuts import redirect, render
from django.contrib import messages
from asc_management.models import Course, Department, School, Semester, Session

from hod.forms import AddCourseForm, AddLecturerForm, AddSchoolForm, AddDepartmentForm, AddSessionForm, AddStudentForm, EditStudentForm
from lecturer.models import Lecturer, LecturerAddition, User
from student.models import Student, StudentAddition

# Create your views here.


def home(request):
    return render(request, 'hod/home.html')


def add_lecturer(request):
    if request.method == "POST":
        form = AddLecturerForm(request.POST)
        if form.is_valid():
            firstname = form.cleaned_data["firstname"]
            lastname = form.cleaned_data["lastname"]
            title = form.cleaned_data["title"]
            address = form.cleaned_data["address"]
            email = form.cleaned_data["email"]
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            lecturer_number = form.cleaned_data["lecturer_number"]

            try:
                lecturer = User.objects.create_user(
                    username=username,
                    password=password,
                    first_name=firstname,
                    last_name=lastname,
                    email=email,
                    type=User.Types.LECTURER
                )

                lecturer_addition = LecturerAddition.objects.create(
                    user=lecturer,
                    title=title,
                    lecturer_number=lecturer_number,
                    address=address
                )

                lecturer.save()
                lecturer_addition.save()
                messages.success(request, "Successfully added lecturer")
                return redirect('hod:add_lecturer')

            except IntegrityError:
                messages.error(request, 'Username already exist')
                return redirect('hod:add_lecturer')

            except:
                messages.error(request, 'Unable to add student')
                return redirect('hod:add_lecturer')
    form = AddLecturerForm(request.POST)
    context = {'form': form}
    return render(request, 'hod/add_lecturer.html', context)


def set_current_session(request):
    if request.method == 'POST':
        select_session = request.POST.get('current_session')
        sessions = Session.objects.all()
        for session in sessions:
            session.is_current_session = False
            session.save()
            
        current_session = Session.objects.get(id=select_session)
        current_session.is_current_session = True
        current_session.save()
        
        
    sessions = Session.objects.all()
    context = {'sessions': sessions}
    return render(request, 'hod/set_current_session.html', context)


def set_current_semester(request):
    if request.method == 'POST':
        select_semester = request.POST.get('current_semester')
        semesters = Semester.objects.all()
        for semester in semesters:
            semester.is_current_semester = False
            semester.save()
            
        current_semester = Semester.objects.get(id=select_semester)
        current_semester.is_current_semester = True
        current_semester.save()
        
        
    semesters = Semester.objects.all()
    context = {'semesters': semesters}
    return render(request, 'hod/set_current_semester.html', context)

def manage_lecturer(request):
    lecturers = Lecturer.objects.all()
    context = {
        "lecturers": lecturers
    }
    return render(request, "hod/manage_lecturer.html", context)


def add_school(request):
    if request.method == "POST":
        form = AddSchoolForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            dean = form.cleaned_data.get('dean')

            try:
                school = School.objects.create(dean=dean, name=name)
                school.save()
            except:
                messages.error(request, 'Unable to add school')
                return redirect('hod:add_school')

    form = AddSchoolForm()
    context = {'form': form}
    return render(request, 'hod/add_school.html', context)


def add_department(request):
    if request.method == 'POST':
        form = AddDepartmentForm(request.POST)
        if form.is_valid():
            hod = form.cleaned_data.get('hod')
            name = form.cleaned_data.get('name')
            school = form.cleaned_data.get('school')

            try:
                department = Department.objects.create(
                    hod=hod, name=name, school=school)
                department.save()
                messages.success(request, 'Successfully added department')
                return redirect('hod:add_department')
            except:
                messages.error(request, 'Unable to add department')
                return redirect('hod:add_department')

    form = AddDepartmentForm()
    context = {'form': form}
    return render(request, 'hod/add_department.html', context)


def manage_department(request):
    departments = Department.objects.all()
    context = {'departments': departments}
    return render(request, 'hod/manage_department.html', context)


def add_session(request):
    if request.method == "POST":
        form = AddSessionForm(request.POST)
        if form.is_valid():
            start = form.cleaned_data.get('start')
            end = form.cleaned_data.get('end')

            session = Session(start=start, end=end)
            session.save()
            messages.success(request, 'Successfully added session')
            return redirect('hod:add_session')

    form = AddSessionForm()
    context = {'form': form}
    return render(request, 'hod/add_session.html', context)


def manage_session(request):
    sessions = Session.objects.all()
    context = {'sessions': sessions}
    return render(request, 'hod/manage_session.html', context)


def add_student(request):
    if request.method == 'POST':
        form = AddStudentForm(request.POST, request.FILES)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            other_name = form.cleaned_data.get('other_name')
            gender = form.cleaned_data.get('gender')
            dob = form.cleaned_data.get('dob')
            phone_number = form.cleaned_data.get('phone_number')
            address = form.cleaned_data.get('address')
            index_number = form.cleaned_data.get('index_number')
            start = form.cleaned_data.get('session_start')
            end = form.cleaned_data.get('session_end')
            department = form.cleaned_data.get('department')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            profile_pic = form.files.get('profile_pic')
            department_obj = Department.objects.get(id=department)
            start_obj = Session.objects.get(id=start)
            end_obj = Session.objects.get(id=end)

            student = User.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                username=username,
                email=email,
                password=password,
                type=User.Types.STUDENT
            )

            student_addition = StudentAddition.objects.create(
                user=student,
                othername=other_name,
                gender=gender,
                dob=dob,
                phone_number=phone_number,
                address=address,
                index_number=index_number,
                department=department_obj,
                start=start_obj,
                end=end_obj,
                profile_pic=profile_pic
            )

            student.save()
            student_addition.save()
            messages.success(request, "Successfully added student")
            return redirect('hod:add_student')
    form = AddStudentForm()
    context = {'form': form}
    return render(request, 'hod/add_student.html', context)


def manage_student(request):
    students = Student.objects.all()
    context = {
        "students": students
    }
    return render(request, "hod/manage_student.html", context)


def edit_student(request, pk):
    if request.method == 'POST':
        form = EditStudentForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            other_name = form.cleaned_data.get('other_name')
            gender = form.cleaned_data.get('gender')
            dob = form.cleaned_data.get('dob')
            phone_number = form.cleaned_data.get('phone_number')
            address = form.cleaned_data.get('address')
            index_number = form.cleaned_data.get('index_number')
            start = form.cleaned_data.get('session_start')
            end = form.cleaned_data.get('session_end')
            department = form.cleaned_data.get('department')
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            department_obj = Department.objects.get(id=department)
            start_obj = Session.objects.get(id=start)
            end_obj = Session.objects.get(id=end)

            student = Student.objects.get(id=pk)
            student.first_name = first_name
            student.last_name = last_name
            student.username = username
            student.more.gender = gender
            student.more.department = department_obj
            student.more.start = start_obj
            student.more.end = end_obj
            student.more.index_number = index_number
            student.more.dob = dob
            student.email = email

hod/templates/hod/add_course.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Add Course 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Add Course</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      
      {% include 'hod/form.html' with form=form messages=messages button_text="Add Course" %}

    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/add_department.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Add department 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Add Department</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      {% include 'hod/form.html' with form=form messages=messages button_text="Add Department" %}
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/add_lecturer.html
{% extends 'hod/base.html' %} {% block page_title %} Add lecturer
{% endblock page_title %} {% load static %} {% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Add lecturer</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      {% include 'hod/form.html' with form=form messages=messages button_text="Add Lecturer" %}
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/add_student.html
{% extends 'hod/base.html' %} {% block page_title %} Add student
{% endblock page_title %} {% load static %} {% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Add student</h3>
      </div>
      
      {% include 'hod/form.html' with form=form messages=messages button_text="Add Student" %}
      
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/edit_course_template.html
{% extends 'hod_template/base_template.html' %} 
{% load static %} 
{% block page_title %} 
Edit Course 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Edit Course</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form method="POST">
        {% csrf_token %}
        <div class="card-body">
          <div class="form-group">
            <label for="course_code">Course title</label>
            <input
              type="text"
              class="form-control"
              name="course_title"
              value="{{ course.course_title }}"
              placeholder="Enter Course title"
            />
          </div>
          <div class="form-group">
            <label for="course_code">Course code</label>
            <input
              type="text"
              class="form-control"
              name="course_code"
              value="{{ course.course_code }}"
              placeholder="Enter course code"
            />
          </div>
          <div class="form-group">
            <label>Department</label>
            <select class="form-control" name="department" {% if course.department == department.id %}selected{% endif %}>
                {% for department in departments %}
                    <option value="{{ department.id }}">{{ department.department_name }}</option>
                {% endfor %}
            </select>
          </div>
          <div class="form-group">
            <label>Staff</label>
            <select class="form-control" name="staff" {% if course.staff_id == staff.id %}selected{% endif %}>
                {% for staff in staffs %}
                    <option value="{{ staff.id }}">{{ staff.admin.first_name }} {{ staff.admin.last_name }}</option>
                {% endfor %}
            </select>
          </div>

          <!-- /.card-body -->
          <div class="form-group">
            {% if messages %}
            
            {% for message in messages %} 
            {% if message.tags == 'error' %}
            <div class="alert alert-danger" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% if message.tags == 'success' %}
            <div class="alert alert-success" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% endfor %} 
            {% endif %}
          </div>
        </div>

        <div class="card-footer">
          <button type="submit" class="btn btn-primary btn-block">
            Edit Course
          </button>
        </div>
      </form>
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/edit_department_template.html
{% extends 'hod_template/base_template.html' %} 
{% load static %} 
{% block page_title %} 
Edit department 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Edit Department</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form method="POST">
        {% csrf_token %}
        <div class="card-body">
          <div class="form-group">
            <label for="title">Department Name</label>
            <input
              type="text"
              class="form-control"
              value="{{ department.department_name }}"
              name="department_name"
              placeholder="Enter department name"
            />
          </div>
          <!-- /.card-body -->
          <div class="form-group">
            {% if messages %}
            
            {% for message in messages %} 
            {% if message.tags == 'error' %}
            <div class="alert alert-danger" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% if message.tags == 'success' %}
            <div class="alert alert-success" style="margin-top: 10px">
              {{ message }}
            </div>
            {% endif %} 
            {% endfor %} 
            {% endif %}
          </div>
        </div>

        <div class="card-footer">
          <button type="submit" class="btn btn-primary btn-block">
            Edit Department
          </button>
        </div>
      </form>
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

hod/templates/hod/form.html
<form method="POST"  enctype="multipart/form-data">
  {% csrf_token %}
  <div class="card-body">

    {% for field in form %}
    <div class="form-group">
      {{ field.error }}
      {{ field.label_tag }}
      {{ field }}
    </div>
    <div class="form-group">
    {% endfor %}
        
      {% if messages %}
      {% for message in messages %}
      {% if message.tags == 'error' %}
      <div class="alert alert-danger" style="margin-top: 10px">{{ message }}</div>
      {% endif %}
      {% if message.tags == 'success' %}
      <div class="alert alert-success" style="margin-top: 10px">{{ message }}</div>
      {% endif %}
      {% endfor %}
        
        
      {% endif %}
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary btn-block">{{ button_text }}</button>
      </div>
    
  </div>
</form>

    

hod/templates/hod/form_user.html
<form method="POST"  enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card-body">
  
      {% for field in form_student %}
        <div class="form-group">
          {{ field.error }}
          {{ field.label_tag }}
          {{ field }}
        </div>
      {% endfor %}
      {% for field in form_student_addition %}
        <div class="form-group">
          {{ field.error }}
          {{ field.label_tag }}
          {{ field }}
        </div>
      {% endfor %}


        
        
        {% if messages %}
        {% for message in messages %}
        {% if message.tags == 'error' %}
        <div class="alert alert-danger" style="margin-top: 10px">{{ message }}</div>
        {% endif %}
        {% if message.tags == 'success' %}
        <div class="alert alert-success" style="margin-top: 10px">{{ message }}</div>
        {% endif %}
        {% endfor %}
          
          
        {% endif %}
    
        <div class="card-footer">
          <button type="submit" class="btn btn-primary btn-block">{{ button_text }}</button>
        </div>
    </div>
      </div>
    </div>
  </form>
  
      

hod/templates/hod/manage_department.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Manage department 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">

     
        <div class="card-header">
          <h3 class="card-title">Manage departments</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px">
              <input
                type="text"
                name="table_search"
                class="form-control float-right"
                placeholder="Search"
              />

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>Department name</th>
                <th>School</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                {% for department in departments %}
                <tr>
                    <td>{{ department.name }}</td>
                    <td>{{ department.school.name }}</td>
                    <td><a href="/edit_department/{{ department.id }}" class="btn btn-success"> Edit</a></td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      
      <!-- /.card -->
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/manage_lecturer.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Manage Lecturer 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      {% comment %} <div class="card-header">
        <h3 class="card-title">Manage Lecturer</h3>
      </div> {% endcomment %}
      <!-- /.card-header -->
      <!-- form start -->

     
        <div class="card-header">
          <h3 class="card-title">Manage Lecturers</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px">
              <input
                type="text"
                name="table_search"
                class="form-control float-right"
                placeholder="Search"
              />

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>Lecturer Number</th>
                <th>Name</th>
                <th>Username</th>
                <th>Adress</th>
                {% comment %} <th>Reason</th> {% endcomment %}
              </tr>
            </thead>
            <tbody>
                {% for lecturer in lecturers %}
                <tr>
                    <td>{{ lecturer.lecturer_number }}</td>
                    <td>{{ lecturer.more.title }} {{ lecturer.first_name }} {{ lecturer.last_name }}</td>
                    <td>{{ lecturer.username }} </td>
                    <td>{{ lecturer.more.address}}</td>
                    <td><a href="/edit_Lecturer/{{ Lecturer.id }}" class="btn btn-success"> Edit</a></td>

                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      
      <!-- /.card -->
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/manage_session.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Manage session 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      {% comment %} <div class="card-header">
        <h3 class="card-title">Manage session</h3>
      </div> {% endcomment %}
      <!-- /.card-header -->
      <!-- form start -->

     
        <div class="card-header">
          <h3 class="card-title">Manage sessions</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px">
              <input
                type="text"
                name="table_search"
                class="form-control float-right"
                placeholder="Search"
              />

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>Start Year</th>
                <th>End Year</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                {% for session in sessions %}
                <tr>
                    <td>{{ session.start }}</td>
                    <td>{{ session.end }}</td>
                    <td><a href="/edit_session/{{ session.id }}" class="btn btn-success"> Edit</a></td>

                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      
      <!-- /.card -->
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/manage_student.html
{% extends 'hod/base.html' %} 
{% load static %} 
{% block page_title %} 
Manage student 
{% endblock page_title %} 
{% block main_content %}
<section class="content">
  <div class="container-fluid">
    <div class="card card-primary">
      {% comment %} <div class="card-header">
        <h3 class="card-title">Manage student</h3>
      </div> {% endcomment %}
      <!-- /.card-header -->
      <!-- form start -->

     
        <div class="card-header">
          <h3 class="card-title">Manage students</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px">
              <input
                type="text"
                name="table_search"
                class="form-control float-right"
                placeholder="Search"
              />

              <div class="input-group-append">
                <button type="submit" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>Index Number</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Profile Picture</th>
                <th>Department</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ student.more.index_number }}</td>
                    <td>{{ student.first_name }} {{ student.last_name }}</td>
                    <td>{{ student.more.gender }} </td>
                    <td><img src="{{ student.more.profile_pic.url }}" height=50px width=50px> </td>
                    <td>{{ student.more.department.name }} </td>
                    <td><a href="{% url 'hod:edit_student' pk=student.id %}" class="btn btn-success"> Edit</a></td>

                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      
      <!-- /.card -->
    </div>
  </div>
</section>

{% endblock %}

hod/templates/hod/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item">
        <h4 class="nav-link">Student management system</h4>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}" >
          Logout
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->